Project restructure
BroadcomMFD/test4z pull request #31
Opened 2022-04-06 10:14 UTC by hizir-bc

2022-04-06 10:15 UTC, hizir-bc commented
Documentation is remaining, please don't merge until the doc work is done ❌

2022-04-06 12:33 UTC, vibhor-bc requested changes

2022-04-06 12:33 UTC, vibhor-bc commented on samples/python/src/test/update/diagnostic_test.py
> +def test_diagnostic():
This script doesn't tests anything rather just prints the API response. So it makes more sense to move it to utility folder.

2022-04-06 14:46 UTC, hizir-bc commented
> As DiagnosticCheck.ts is required only for typescript samples so moving it under nodejs folder will make more sense.

done

2022-04-06 14:46 UTC, hizir-bc commented
Tech writer review is pending for the readme files

2022-04-06 14:53 UTC, hizir-bc commented
Tech writer review is pending ❌

2022-04-08 09:43 UTC, hizir-bc commented
All the code changes are in placed, can be reviewed.

2022-04-14 14:19 UTC, vibhor-bc commented
Waiting for merge until SDK 2.0.0 release.

2022-04-20 11:56 UTC, hizir-bc commented
end-to-end test successful ✅

2022-04-26 10:09 UTC, merged