Us821713 zos connect working sample
BroadcomMFD/test4z pull request #59
Opened 2022-05-19 10:05 UTC by dusan-bc

z/OS Connect changes, please review

2022-05-19 10:44 UTC, vahidbaharvand commented on supportive_cases/zos-connect/README.md
> +This folder contains test sample for triggering an API endpoint through z/OS Connect to place order in the CICS Catalog manager example application. Prior to this we check the status of stock of the
This folder contains a test sample that triggers an API endpoint through z/OS Connect. The sample places an order in the CICS Catalog manager of the example application. First it checks the status of the stock of the item. After the order is placed, it validates the success by checking the stock again.

2022-05-19 10:44 UTC, vahidbaharvand commented on supportive_cases/zos-connect/README.md
> +z/OS instance set up and running
Not necessary. It is already stated in the preprequisites of the main readme.

2022-05-19 10:44 UTC, vahidbaharvand commented on supportive_cases/zos-connect/README.md
> +CICS Catalog manager example application with webservice enabled
* The CICS Catalog manager example application with webservice is enabled.
* The connection between z/OS Connect and the CICS region is established.

2022-05-19 13:32 UTC, vibhor-bc requested changes

2022-05-19 13:32 UTC, vibhor-bc commented on supportive_cases/zos-connect/package.json
> +    "@broadcom/test4z": "1.3.0",
The SDK version should be 2.0.0.

2022-05-19 13:32 UTC, vibhor-bc commented on supportive_cases/zos-connect/Test4zMatchers.ts
> +}
This matcher can be removed as its not being used.

2022-05-19 13:32 UTC, vibhor-bc commented on supportive_cases/zos-connect/jest.setup.js
> +    toBeHaveTestData,
Can be removed .

2022-05-19 13:32 UTC, vibhor-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        console.log(JSON.stringify(output));
Replacing console.log with an expect on the output string will ensure that the records are updated and the request was successful.

2022-05-19 13:32 UTC, vibhor-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        console.log("Content of the WS-IN-STOCK field after the order: " + JSON.stringify(recordAfter));
console.log can be removed.

2022-05-19 13:32 UTC, vibhor-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        console.log("Content of the WS-IN-STOCK field before the order: " + JSON.stringify(recordBefore));
This can be replaced with an expect which checks for some non null value.

2022-05-19 14:11 UTC, dusan-bc commented on .scripts/setZosConnect.sh
> +printf "\nCA View information collected successfully\n\n"
Missed that one, fixing

2022-05-19 14:14 UTC, dusan-bc commented on supportive_cases/zos-connect/jest.setup.js
> +    toBeHaveTestData,
removing

2022-05-19 14:18 UTC, dusan-bc commented on zowe.schema.json
> +                                                "description": "The zosconnect server host name."
fixed

2022-05-19 14:46 UTC, dusan-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        console.log(JSON.stringify(output));
fixed as requested

2022-05-19 14:46 UTC, dusan-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        console.log("Content of the WS-IN-STOCK field after the order: " + JSON.stringify(recordAfter));
done

2022-05-19 14:47 UTC, dusan-bc commented on supportive_cases/zos-connect/package.json
> +    "@broadcom/test4z": "1.3.0",
changed

2022-05-20 08:07 UTC, vibhor-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        let requestBody = {DFH0XCMNOperation : {ca_order_request: {ca_item_ref_number: 20, ca_quantity_req: 1}}};
i think it will probably make more sense to replace the hard coded item_reference_number 20 with the value from the recordBefore. This way the test will be guaranteed to work with the same record.

2022-05-20 10:36 UTC, dusan-bc commented on supportive_cases/zos-connect/src/test/zosConnectSample.test.ts
> +        let requestBody = {DFH0XCMNOperation : {ca_order_request: {ca_item_ref_number: 20, ca_quantity_req: 1}}};
Changed as requested, itemRef is externalized and taken from the record we choose

2022-05-20 11:10 UTC, vibhor-bc approved these changes

2022-05-20 11:11 UTC, merged