Document changelog
BroadcomMFD/test4z pull request #74
Opened 2022-06-27 11:58 UTC by vahidbaharvand

2022-06-27 12:41 UTC, vibhor-bc requested changes

2022-06-27 12:41 UTC, vibhor-bc commented on CHANGELOG.md
> +- Added the mock server.
We also have samples demonstrating compare with different layouts & restructuring of samples.

2022-06-27 12:41 UTC, vibhor-bc commented on CHANGELOG.md
> +## [2.0.0] 2022-03-22
The date should be changed.

2022-06-27 12:41 UTC, vibhor-bc commented on README.md
> +- Exclude feature of the Compare endpoint requires a certain File Master Plus version 12.0 and the required PTF installation. Make sure you have the required PTF to be able to use the field exclusion
I think we should not mention the backend service components. It should be taken care by the service installation admin. The version of samples are compatible with the specific version of service installation.

2022-06-28 08:46 UTC, vibhor-bc approved these changes

2022-06-30 09:14 UTC, hizir-bc approved these changes

2022-06-30 09:51 UTC, hizir-bc requested changes
For this release there should be an item for **Restructuring the samples**

2022-07-01 06:23 UTC, hizir-bc approved these changes

2022-07-01 06:23 UTC, merged