implementing the service changes to the samples
BroadcomMFD/test4z pull request #79
Opened 2022-06-30 15:06 UTC by hizir-bc

2022-06-30 16:17 UTC, sergiuilie requested changes

2022-06-30 16:17 UTC, sergiuilie commented on samples/python/src/main/model/search/SearchModel.py
> +        self.copybook = copy_book
Should we change the param name from copy_book to copybook as well?

2022-07-01 06:21 UTC, hizir-bc commented on samples/python/src/main/model/search/SearchModel.py
> +        self.copybook = copy_book
param name follows the python naming convention. Better as it is

2022-07-01 07:55 UTC, vibhor-bc approved these changes

2022-07-01 08:38 UTC, sergiuilie approved these changes

2022-07-01 08:39 UTC, merged